FROM node:22-alpine AS build
WORKDIR /app
RUN apk add --no-cache git python3 make g++
COPY client/package*.json ./
RUN npm ci --no-audit --prefer-offline
COPY client/ ./
RUN npm run build

FROM nginx:stable-alpine AS runtime
COPY --from=build /app/dist/client/browser /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]